### ISSUE TITLE
Stuck at npm install

### ISSUE THREAD

**Issue by rockydares** [shivamguys/irctc-cypress-automation#30]
On windows process is stuck on `reify:rxjs: timing reifyNode:node_modules/lodash Completed in 2284ms`
It doesn't go beyond this. Latest npm is installed. 
Any help?

**Comment by shivamguys** [comment]
Would advise you to go through these links sometimes some packages hangs while installing this is due to wrong proxy configuration or sometimes permission issues on os level.


https://luisrangelc.medium.com/comprehensive-guide-to-clearing-the-npm-cache-on-linux-macos-and-windows-d38d5c6405aa


https://stackoverflow.com/questions/16873973/npm-install-hangs

**Comment by rockydares** [comment]
Thank you, this solved the problem.
But I encountered a new issue, while auto captcha on, on captch input box it says, `python was not found`. Python is added on path on my windows.
